//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllPosition
    {
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<long> JobTotalViews { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> NoOfVacancy { get; set; }
        public Nullable<bool> IsPositionOpen { get; set; }
        public string EmployementType { get; set; }
        public string SalaryRange { get; set; }
        public Nullable<int> GenderSpecification { get; set; }
        public Nullable<int> MinExperinceYear { get; set; }
        public Nullable<System.DateTime> LastDateOfJob { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
