//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cand_JobFilledByHr
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Grade { get; set; }
        public string Department { get; set; }
        public string EmpCode { get; set; }
        public string CarAllow { get; set; }
        public string Designation { get; set; }
        public string Division { get; set; }
        public string Unit { get; set; }
        public string CarBike { get; set; }
    
        public virtual User User { get; set; }
    }
}
