//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateQualification
    {
        public int id { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public string InstitutionName { get; set; }
        public string DegreeName { get; set; }
        public Nullable<int> DegreeId { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> DgrFrmMonth { get; set; }
        public Nullable<int> DgrFrmYear { get; set; }
        public Nullable<int> DgrToMonth { get; set; }
        public Nullable<int> DgrToYear { get; set; }
        public Nullable<bool> isOngoing { get; set; }
        public Nullable<int> ResultTypeId { get; set; }
        public string ResultType { get; set; }
        public string ResultValue { get; set; }
    
        public virtual candidate candidate { get; set; }
    }
}
