//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateJobApply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateJobApply()
        {
            this.HrShortlistings = new HashSet<HrShortlisting>();
        }
    
        public int Id { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
        public Nullable<bool> ApplyByCV { get; set; }
    
        public virtual AllPosition AllPosition { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrShortlisting> HrShortlistings { get; set; }
    }
}
