//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateExperince
    {
        public int id { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public string CompanyName { get; set; }
        public string DesignationName { get; set; }
        public string Locationname { get; set; }
        public Nullable<int> FromMonth { get; set; }
        public Nullable<int> FromYear { get; set; }
        public Nullable<int> ToMonth { get; set; }
        public Nullable<int> ToYear { get; set; }
        public Nullable<bool> IsPresent { get; set; }
        public string ReasonForLeaving { get; set; }
        public Nullable<decimal> InitialSalary { get; set; }
        public Nullable<decimal> CurrentSalary { get; set; }
        public string JobDuties { get; set; }
        public Nullable<bool> FreshGraduate { get; set; }
    
        public virtual candidate candidate { get; set; }
    }
}
