//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using CareerPortal.CustomAttributes;
    using System;
    using System.Collections.Generic;
    
    public partial class cndEvMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cndEvMaster()
        {
            this.cndEvDetails = new HashSet<cndEvDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AdditionalComments { get; set; }
        public Nullable<int> IntEvDecisionId { get; set; }
        [RequiredIf(nameof(IntEvDecisionId), "1", ErrorMessage = "Joining Date Is Required If Candidate Selected")]
        public Nullable<System.DateTime> JoinDate { get; set; }

        [RequiredIf(nameof(IntEvDecisionId), "1", ErrorMessage = "Salary Is Required If Candidate Selected")]
        public Nullable<double> Salary { get; set; }

        [RequiredIf(nameof(IntEvDecisionId), "1", ErrorMessage = "Designation Is Required If Candidate Selected")]
        public Nullable<int> DesignationId { get; set; }

        [RequiredIf(nameof(IntEvDecisionId), "1", ErrorMessage = "Grade Is Required If Candidate Selected")]
        public Nullable<int> GradeId { get; set; }
        [RequiredIf(nameof(IntEvDecisionId), "1", ErrorMessage = " Department Required If Candidate Selected")]
        public Nullable<int> DepartmentId { get; set; }
        [RequiredIf(nameof(IntEvDecisionId), "1", ErrorMessage = "Benifites Is Required If Candidate Selected")]
        public string Benifits { get; set; }
        public Nullable<int> fdGivenBy { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<double> TotalMarks { get; set; }
        public Nullable<double> ObtainedMarks { get; set; }
        public Nullable<int> ShortListId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cndEvDetail> cndEvDetails { get; set; }
        public virtual User User { get; set; }
        public virtual IntEvDecision IntEvDecision { get; set; }
        public virtual User User1 { get; set; }
        public virtual HrShortlisting HrShortlisting { get; set; }
    }
}
