//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cndEvDetail
    {
        public int Id { get; set; }
        public Nullable<int> cndEvMasterId { get; set; }
        public Nullable<int> MapId { get; set; }
        public Nullable<double> obtainMarks { get; set; }
    
        public virtual cndEvMaster cndEvMaster { get; set; }
        public virtual IntQuestionMapping IntQuestionMapping { get; set; }
    }
}
