//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CareerPortalEntities : DbContext
    {
        public CareerPortalEntities()
            : base("name=CareerPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<CandidateQualification> CandidateQualifications { get; set; }
        public virtual DbSet<CandidateExperince> CandidateExperinces { get; set; }
        public virtual DbSet<AllPosition> AllPositions { get; set; }
        public virtual DbSet<CandidateJobApply> CandidateJobApplies { get; set; }
        public virtual DbSet<LangScoreType> LangScoreTypes { get; set; }
        public virtual DbSet<LanguageMaping> LanguageMapings { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LanguageScore> LanguageScores { get; set; }
        public virtual DbSet<CandidateLang> CandidateLangs { get; set; }
        public virtual DbSet<Cand_AMPreviousWork> Cand_AMPreviousWork { get; set; }
        public virtual DbSet<Cand_Dependants> Cand_Dependants { get; set; }
        public virtual DbSet<Cand_JobFilledByHr> Cand_JobFilledByHr { get; set; }
        public virtual DbSet<Cand_RelateFreindWorking> Cand_RelateFreindWorking { get; set; }
        public virtual DbSet<MoseRecentEmployement> MoseRecentEmployements { get; set; }
    
        public virtual ObjectResult<usp_getallDegree_Result> usp_getallDegree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getallDegree_Result>("usp_getallDegree");
        }
    }
}
