//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrShortlistingDetail
    {
        public int Id { get; set; }
        public Nullable<int> ShortListId { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<int> SlotId { get; set; }
        public Nullable<bool> IsSendJobForm { get; set; }
        public Nullable<bool> IsEmailSend { get; set; }
        public Nullable<bool> IsInterviewConfirmed { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> PanelId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DecisionId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual HrShortlisting HrShortlisting { get; set; }
        public virtual User User { get; set; }
        public virtual IntEvDecision IntEvDecision { get; set; }
        public virtual InterviewPanel InterviewPanel { get; set; }
        public virtual TimingSlot TimingSlot { get; set; }
    }
}
