//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrShortlisting
    {
        public int Id { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> CandApplyId { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<int> SlotId { get; set; }
        public Nullable<bool> IsSendJobForm { get; set; }
    public Nullable<bool> IsEmailSend { get; set; } = true;
        public Nullable<bool> IsInterviewComfirmed { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AllPosition AllPosition { get; set; }
        public virtual CandidateJobApply CandidateJobApply { get; set; }
        public virtual User User { get; set; }
        public virtual TimingSlot TimingSlot { get; set; }
    }
}
