//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrShortlisting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrShortlisting()
        {
            this.cndEvMasters = new HashSet<cndEvMaster>();
            this.HrShortlistingDetails = new HashSet<HrShortlistingDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> CandApplyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> EvDecisionId { get; set; }
    
        public virtual AllPosition AllPosition { get; set; }
        public virtual CandidateJobApply CandidateJobApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cndEvMaster> cndEvMasters { get; set; }
        public virtual IntEvDecision IntEvDecision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrShortlistingDetail> HrShortlistingDetails { get; set; }
    }
}
