//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntEvQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IntEvQuestion()
        {
            this.IntQuestionMappings = new HashSet<IntQuestionMapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IntEvQTypeId { get; set; }
        public string EvaluationType { get; set; }
    
        public virtual IntEvaluationType IntEvaluationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntQuestionMapping> IntQuestionMappings { get; set; }
    }
}
