//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageMaping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LanguageMaping()
        {
            this.CandidateLangs = new HashSet<CandidateLang>();
        }
    
        public int Id { get; set; }
        public Nullable<int> langgId { get; set; }
        public Nullable<int> ScoreTypeId { get; set; }
        public Nullable<int> ScoreId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual LangScoreType LangScoreType { get; set; }
        public virtual Language Language { get; set; }
        public virtual LanguageScore LanguageScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateLang> CandidateLangs { get; set; }
    }
}
