//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.candidates = new HashSet<candidate>();
            this.CandidateJobApplies = new HashSet<CandidateJobApply>();
        }
    
        public int Id { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
        public string UserPhoneNo { get; set; }
        public string UserImage { get; set; }
        public Nullable<bool> IsEmailVerify { get; set; }
        public Nullable<bool> isNewPassword { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string FullName { get; set; }
        public string CandidateCVPath { get; set; }
        public string EmailTokens { get; set; }
        public Nullable<System.DateTime> CVUpdatedOn { get; set; }
        public Nullable<bool> isCandidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidate> candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateJobApply> CandidateJobApplies { get; set; }
    }
}
